# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-07-16 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='\u4e66\u540d')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='\u5b9a\u4ef7')),
            ],
        ),
    ]
