# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-07-16 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='info',
            field=models.CharField(default='', max_length=100, verbose_name='\u63cf\u8ff0'),
        ),
    ]
