# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-07-23 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20210717_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u6d3b\u8dc3'),
        ),
    ]
